### ISSUE TITLE
Feature - display three sine waves on graph with X axis for time

### ISSUE THREAD

**Issue by quozl** [sugarlabs/biorhythm#9]
Biorhythm theory is based on three sine waves of different frequencies originating at birth.

Add a feature to display these sine waves on a graph with the X axis for time, covering a week before and a week after the selected date.

This will (a) illustrate the effect of sine waves of different frequencies, and (b) provide more visual data for building a confirmation bias.  :grin:

**Comment by nswarup14** [comment]
1) Should the graph be displayed on the click of a Sugar button or can it be made to appear by default?
2) Should the graph be interactive? On moving a slider the scale of the x and y axes could change, thereby providing an interactive way for the child to engage.
3) Should the graphs include an option to change/extend the duration of the time period from week before and week after birth to a arbitrary set of dates?

Thanks!

**Comment by quozl** [comment]
Thanks for the questions.  But I'll leave it for you to decide or for others to comment.  There's some waveform code in the Measure activity, but I don't know how useful it would be.

**Comment by nswarup14** [comment]
@quozl 
Thanks!
I shall have a look at it.

**Comment by rhl-bthr** [comment]
My opinion,
1. by default
2. yes
3. yes
I am not sure how to do 2 and 3, but it'd be good if they can be added

**Comment by nswarup14** [comment]
@pro-panda 
I'm sorry I didn't quite understand what points 2 and 3 signify.

Thanks.

**Comment by quozl** [comment]
To your three questions in https://github.com/sugarlabs/biorhythm/issues/9#issuecomment-501521375.
